### ISSUE TITLE
A bad case of event.

### ISSUE THREAD

**Issue by malash** [nofluxjs/noflux-state#2]
我在使用`eventemitter2`实现部分监听功能的时候遇到一个`bad case`：https://github.com/nofluxjs/state/blob/next-event-bad-case/test/state.js#L68

```
test('event emit with cursor', t => {
  t.plan(3);
  const state = new State();
  process.nextTick(() => {
    state.set('', 1); // 这里没有被正确的监听
    state.set('a', 1);
    state.set('a.b', 1);
    state.set('c.d', 1);
  });
  return Observable
    .from(state.cursor('a').listen('change'))
    .map(() => t.pass())
    .timeoutWith(OBSERVABLE_TIMEOUT, Observable.empty());
});
```

在这个`case`中，使用`eventemitter2`的[namespace](https://github.com/asyncly/EventEmitter2#multi-level-wildcards)可以实现对子状态的部分监听：

如调用`state.cursor('a').listen('change')`，那么可以监听到对`a`和`a.b`的`set`操作，在其内部使用`emitter.on('change.a.**')`实现；但是，这种实现没有办法监听到`''`（也就是`a`的父节点，即根节点）的修改。

我认为有必要对监听行为使用树状结构存储，对任何结点的遍历需要进行两步操作：遍历其全部祖先监听 和 遍历其子树全部监听。

我需要调研下`eventemitter2`或类似的实现，如果没有可用的就要造轮子了。

**Comment by ssnau** [comment]
> 但是，这种实现没有办法监听到''（也就是a的父节点，即根节点）的修改。

我觉得原`dataton`不存在这样的问题吧。也不建议内部依赖`eventemitter`，如果有`listen`，永远要记得`remove`，但很容易遗忘。

**Comment by malash** [comment]
@ssnau 可能我没有表达清楚，原`dataton`不存在这样的问题，是我在实现“部分监听”功能的时候遇到的。

1. “部分监听”指使用`@connect`时可以使用`@connect('sub.path')`只监听部分路径的变化，减少`forceUpdate`次数

2. 之所以把`event emitter`做进了`State`中，是为了便于分别支持`React`和`Vue`框架，当然这可能有更好的解决方式

**Comment by ssnau** [comment]
@malash IMHO，这个不用eventemitter也很方便实现吧。因为你只需要在监听时，判断`path`是否是以监听的字符串开头即可。https://github.com/ssnau/dataton/blob/master/index.js#L233

**Comment by malash** [comment]
没仔细看文档，原来`eventemitter2`支持`emit('a.**')`这种用法，问题解决了
